version: '3.4'

services:
  nginx-proxy:
    restart: always
    build: ./nginx
    container_name: nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./lagos_bus_route:/lagos_bus_route
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy

  db:
    restart: always
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - lagos_bus_route-data:/var/lib/postgresql/data
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:3.2.11-alpine
    volumes:
      - lagos_bus_route-redis-data:/data
    expose:
      - "6379"

  web:
    restart: always
    depends_on:
      - db
    env_file: env-prod
    environment:
      - SERVICE=web
      - VIRTUAL_HOST=${HOST_NAME}
      - LETSENCRYPT_HOST=${HOST_NAME}
      - LETSENCRYPT_EMAIL=${EMAIL}
    expose:
      - 80
      - 443
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 5s

  celery:
    restart: always
    env_file: env-prod
    environment:
      - SERVICE=celery
    depends_on:
      - db
      - redis
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        failure_action: rollback
        monitor: 5s

volumes:
  lagos_bus_route-data:
  lagos_bus_route-redis-data:
  certs:
  html:
  vhost:
