version: '3.4'

services:

  nginx-proxy:
    volumes:
      - ./lagos_bus_route/staticfiles:/static

  web:
    build: .
    volumes:
      - ./lagos_bus_route:/lagos-bus-route/lagos_bus_route
    stdin_open: true
    tty: true

  celery:
    build: .
    volumes:
      - ./lagos_bus_route:/lagos-bus-route/lagos_bus_route
    stdin_open: true
    tty: true