version: '3.4'

services:

  db:
    environment:
      POSTGRES_USER_FILE: /run/secrets/psql-user
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
      POSTGRES_DB_FILE: /run/secrets/psql-db_name
    secrets:
      - psql-user
      - psql-pw
      - psql-db_name
    volumes:
      - /lagos-bus-route/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - lagos_bus_route-data:/var/lib/postgresql/data

  nginx-proxy:
    volumes:
      - lagos_bus_route-static:/lagos-bus-route/lagos_bus_route/static:ro

  web:
    image: electronitrix/lagosbusroute_web:latest
    volumes:
      - lagos_bus_route-static:/lagos-bus-route/lagos_bus_route/static

  celery:
    image: electronitrix/lagosbusroute_celery:latest

secrets:
  psql-user:
    external: true
  psql-pw:
    external: true
  psql-db_name:
    external: true

volumes:
  lagos_bus_route-static: