version: '3.4'

services:

  nginx-proxy:
    volumes:
      - lagos_bus_route-static:/lagos-bus-route/lagos_bus_route/static:ro

  web:
    build: .
    volumes:
      - lagos_bus_route-static:/lagos-bus-route/lagos_bus_route/static

  celery:
    build: .

volumes:
  lagos_bus_route-static: