secrets:
  psql-db_name:
    external: true
  psql-pw:
    external: true
  psql-user:
    external: true
services:
  celery:
    build:
      context: /Users/nitrix/Projects/lagos-bus-route
    depends_on:
    - db
    - redis
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        failure_action: rollback
        monitor: 5s
        parallelism: 1
    environment:
      ALLOWED_HOSTS: .ngrok.io localhost 104.236.255.174
      DB_HOST: db
      DB_NAME: lagos_bus_route
      DB_PASSWORD: admin
      DB_PORT: '5432'
      DB_USER: nitrix
      DEBUG: "False"
      ENVIRONMENT: PRODUCTION
      PAGE_ACCESS_TOKEN: EAAD84tcqxhABACIqfkx86tL1yqvthZByrHT3QbhhdK7XZBZBG0MbpYUpZCdW0HRI3b0C1OdqRD4FHcTGNQSTptqhoyhxKqdJbF3JBARDiXukvyMSsUUyNNNh8bb0WsZB2YeD9A9uZBdjai3vyhlDKlxDo2C3ZBsAPuE72BZCxsdgyQZDZD
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SECRET_KEY: '@!=-&&7tnoyot57^!_jtix5(#o52u#lavv5+nr2w40u754)1r6'
      SERVICE: celery
      VERIFY_TOKEN: NarutoIpsumDolor
    image: electronitrix/lagosbusroute_celery:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - /Users/nitrix/Projects/lagos-bus-route/lagos_bus_route:/lagos-bus-route/lagos_bus_route:rw
  db:
    environment:
      ALLOWED_HOSTS: .ngrok.io localhost 104.236.255.174
      DB_HOST: db
      DB_NAME: lagos_bus_route
      DB_PASSWORD: admin
      DB_PORT: '5432'
      DB_USER: nitrix
      DEBUG: "False"
      ENVIRONMENT: PRODUCTION
      PAGE_ACCESS_TOKEN: EAAD84tcqxhABACIqfkx86tL1yqvthZByrHT3QbhhdK7XZBZBG0MbpYUpZCdW0HRI3b0C1OdqRD4FHcTGNQSTptqhoyhxKqdJbF3JBARDiXukvyMSsUUyNNNh8bb0WsZB2YeD9A9uZBdjai3vyhlDKlxDo2C3ZBsAPuE72BZCxsdgyQZDZD
      POSTGRES_DB: /run/secrets/psql-db_name
      POSTGRES_PASSWORD: /run/secrets/psql-pw
      POSTGRES_USER_FILE: /run/secrets/psql-user
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SECRET_KEY: '@!=-&&7tnoyot57^!_jtix5(#o52u#lavv5+nr2w40u754)1r6'
      VERIFY_TOKEN: NarutoIpsumDolor
    expose:
    - '5432'
    image: postgres:9.6
    restart: always
    secrets:
    - source: psql-db_name
    - source: psql-pw
    - source: psql-user
    volumes:
    - /Users/nitrix/Projects/lagos-bus-route/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw
    - lagos_bus_route-data:/var/lib/postgresql/data:rw
  nginx:
    depends_on:
    - web
    image: nginx:alpine
    ports:
    - published: 8000
      target: 8000
    restart: always
    volumes:
    - /Users/nitrix/Projects/lagos-bus-route/nginx/django.conf:/etc/nginx/conf.d/default.conf:rw
    - /Users/nitrix/Projects/lagos-bus-route/lagos_bus_route/staticfiles:/static:rw
  redis:
    expose:
    - '6379'
    image: redis:3.2.11-alpine
    restart: always
    volumes:
    - lagos_bus_route-redis-data:/data:rw
  web:
    build:
      context: /Users/nitrix/Projects/lagos-bus-route
    depends_on:
    - db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        failure_action: rollback
        monitor: 5s
        parallelism: 1
    environment:
      ALLOWED_HOSTS: .ngrok.io localhost 104.236.255.174
      DB_HOST: db
      DB_NAME: lagos_bus_route
      DB_PASSWORD: admin
      DB_PORT: '5432'
      DB_USER: nitrix
      DEBUG: "False"
      ENVIRONMENT: PRODUCTION
      PAGE_ACCESS_TOKEN: EAAD84tcqxhABACIqfkx86tL1yqvthZByrHT3QbhhdK7XZBZBG0MbpYUpZCdW0HRI3b0C1OdqRD4FHcTGNQSTptqhoyhxKqdJbF3JBARDiXukvyMSsUUyNNNh8bb0WsZB2YeD9A9uZBdjai3vyhlDKlxDo2C3ZBsAPuE72BZCxsdgyQZDZD
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SECRET_KEY: '@!=-&&7tnoyot57^!_jtix5(#o52u#lavv5+nr2w40u754)1r6'
      SERVICE: web
      VERIFY_TOKEN: NarutoIpsumDolor
    expose:
    - '8000'
    image: electronitrix/lagosbusroute_web:latest
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - /Users/nitrix/Projects/lagos-bus-route/lagos_bus_route:/lagos-bus-route/lagos_bus_route:rw
version: '3.4'
volumes:
  lagos_bus_route-data: {}
  lagos_bus_route-redis-data: {}

