# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=22),
        ),
        migrations.AddField(
            model_name='busstop',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=22),
        ),
        migrations.AddField(
            model_name='busstop',
            name='place_id',
            field=models.CharField(default=1, max_length=27),
            preserve_default=False,
        ),
    ]
