# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0003_trigram_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=22),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=22),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='place_id',
            field=models.CharField(max_length=27, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together=set([('latitude', 'longitude')]),
        ),
    ]
