# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-05 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0005_populate_busstop_prod'),
        ('routes', '0002_route_node_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('route_id', 'busstop', 'node_position')]),
        ),
    ]
