# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 20:17
from __future__ import unicode_literals

import json
import os

from django.conf import settings
from django.db import IntegrityError, migrations


def fetch_nodes_in_batches(no_per_batch, start=0):
    """Get route nodes from csv file in batches
    :param no_per_batch: number of nodes to return per batch
    """


def forwards(apps, schema_editor):
    """populate the database with routes from route_node_to_busstop.csv"""
    Route = apps.get_model('routes', 'Route')
    project_dir = os.path.dirname(settings.BASE_DIR)
    routes_json_filename = '{project_dir}/routes/fixtures/routes.json'.format(
        project_dir=project_dir)

    with open(routes_json_filename) as json_data:
        routes = json.load(json_data)

    if Route.objects.filter(busstop_id=routes[0]['busstop_id']).exists():
        Route.objects.bulk_create((Route(**node) for node in routes))


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_node_position'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
